/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Window;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.SwingUtilities;


/**
 *
 * @author morgana
 */
public class PhotoWindow extends javax.swing.JFrame {

    /**
     * Creates new form PhotoWindow
     */
    public PhotoWindow() { 
        initComponents();
        //backButton.setName("backButton");
        //forwardButton.setName("forwardButton");
        setButton(backButton,false);
        setButton(forwardButton,false);
    }

    private void setButton(JButton button, boolean visible){
        button.setOpaque(visible);
        button.setContentAreaFilled(visible);
        button.setBorderPainted(visible);
        slideShowCheck.setVisible(visible);
        if (visible){
            if (slideShowCheck.isEnabled())
                sliderBar.setVisible(true);
            else
                sliderBar.setVisible(false);
            if (button == backButton){
                button.setText("<");
            }
            else 
                button.setText(">");
        } else {
            slideShowCheck.setVisible(false);
            sliderBar.setVisible(false);
            button.setText("");
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        forwardButton = new javax.swing.JButton();
        sliderBar = new javax.swing.JSlider();
        slideShowCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PhotoWindow.this.mouseEntered(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        backgroundPanel.setLayout(new java.awt.BorderLayout());

        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PhotoWindow.this.mouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PhotoWindow.this.mouseEntered(evt);
            }
        });
        backgroundPanel.add(backButton, java.awt.BorderLayout.LINE_START);

        forwardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PhotoWindow.this.mouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PhotoWindow.this.mouseEntered(evt);
            }
        });
        backgroundPanel.add(forwardButton, java.awt.BorderLayout.LINE_END);

        sliderBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PhotoWindow.this.mouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PhotoWindow.this.mouseEntered(evt);
            }
        });
        backgroundPanel.add(sliderBar, java.awt.BorderLayout.PAGE_END);

        slideShowCheck.setText("Slideshow");
        slideShowCheck.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        slideShowCheck.setMargin(new java.awt.Insets(2, 2, 2, 10));
        slideShowCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PhotoWindow.this.mouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PhotoWindow.this.mouseEntered(evt);
            }
        });
        backgroundPanel.add(slideShowCheck, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(backgroundPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEntered
            setButton(forwardButton,true);
            setButton(backButton,true);
    }//GEN-LAST:event_mouseEntered

    private void mouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExited
        setButton(forwardButton,false);
        setButton(backButton,false);
        
    }//GEN-LAST:event_mouseExited

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton forwardButton;
    private javax.swing.JCheckBox slideShowCheck;
    private javax.swing.JSlider sliderBar;
    // End of variables declaration//GEN-END:variables
}
